### ISSUE TITLE
Error after manual installation

### ISSUE THREAD

**Issue by codeyy** [geertmeersman/nexxtmove#24]
I tried to install the integration through the HACS repositories, but I couldn't find it there, so I followed the manual steps. 
It doesn't appear in my HACS integrations, but I am able to add an integration in HA.

However, I get the error:

>  Logger: homeassistant.config_entries
Source: config_entries.py:942
First occurred: 20:10:36 (1 occurrences)
Last logged: 20:10:36
Config entry 'xxx.xxx@xxx.com' for nexxtmove integration not ready yet: Exception 'NoneType' object has no attribute 'split'; Retrying in background

Screenshot of the integration:
![2023-04-20 20_14_54-Instellingen – Home Assistant – Mozilla Firefox](https://user-images.githubusercontent.com/2722590/233453509-4d611244-e96d-4750-95d0-8ae1b868e8c2.png)

I'm no Python coder, but I'm willing to help out wherever I can.
Thanks in advance for the effort already put into this integration.

**Comment by geertmeersman** [comment]
Hi Marijn,

thanks for creating the issue. Is your installation a privately owned one or by a company? I suspect it not having a "price/kwh" assigned. So you would be the first one having an installation without a price assigned.

I will fix it. But could you join me on discord? This will help in debugging: https://discord.gg/PTpExQJsWA

**Comment by geertmeersman** [comment]
New release should be available in Hacs.

Btw concerning the "manual" installation, this is not needed, you just need to add the repository as a custom repository in hacs and it will show up. I am still waiting the merge of my pull request to hacs, but this can take some weeks apparently.

**Comment by codeyy** [comment]
Hey Geert, as mentioned on Discord it works now. Thanks a lot for the integration!
